//CREATE KEYSPACE todos
//WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};


//CREATE TABLE todos ( 
//	id text,
//	description text,
//	PRIMARY KEY (id) 
//);


//insert into todos (id, description) values ('one', 'task one');
//insert into todos (id, description) values ('two', 'task two');
//insert into todos (id, description) values ('three', 'task three');

select * from todos;
